server:
   port: 443
   ssl:
     key-store: classpath:ssl/4698590_www.dbdbd.xyz.jks
     key-password: tJKyJ6xA
spring:
  redis:
    host: localhost
    port: 6379
    password: lucifer
  freemarker:
    suffix: .ftl
# DATASOURCE
jdbc-user:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/oauth2-user?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  #jdbc:mysql://localhost/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=UTC
  username: service
  password: lucifer1qaz@WSX
jdbc:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/carpool?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: lucifer1qaz@WSX

#jdbc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: root
#    password:
#jdbc-hfc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/hfc?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: root
#    password:


# MyBatis

mybatis:
    typeAliasesPackage: com.lucifer
    mapperLocations: classpath:/sql-mapper/*.xml
    configLocation: classpath:/mybatis-config.xml

qiniu:
  accessKey: eeYtcWvGPXqjEiTIxDljeVu8qxFpwdXOvGo4PURq
  secretKey: LHkSG-HRLccuUYSgb-TX0ZcDrsyUMEzSg6Z3GG6G
  publicBucket: vote-2
  url: http://osienakpr.bkt.clouddn.com/
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 30Mb
lucene:
  local: /data/lucene/carpool
sms:
  sendCodeUrl: https://api.netease.im/sms/sendcode.action
  appKey: 80f0cbe03428deb5f520005694aeffdd
  appSecret: ef2c21102cb8
  verifyCodeUrl: https://api.netease.im/sms/verifycode.action
wx:
  appId: wx41dbe3ee3f386699
  secret: 0c367176de4c7db5a26bd542b6b4b2ea





